server:
  port: 80

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: auth-service
          predicates:
            #- Path=/api/v1/auth/**          #localhost/api/v1/auth/findall
            - Path=/auth/**
          uri: http://localhost:7071       #localhost:7071/api/v1/auth/findall
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/auth-service
        - id: user-service
          predicates:
            - Path=/user/**          #localhost/api/v1/user/findall
          uri: http://localhost:7072 #localhost:7071/api/v1/user/findall
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/user-service
        - id: company-service
          predicates:
            - Path=/company/**          #localhost/api/v1/user/findall
          uri: http://localhost:7073      #localhost:7071/api/v1/user/findall
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/company-service
        - id: comment-service
          predicates:
            - Path=/comment/**          #localhost/api/v1/user/findall
          uri: http://localhost:7074      #localhost:7071/api/v1/user/findall
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/comment-service
      default-filters:
        - RewritePath= /(?<segment>.*),/api/v1/$\{segment}
