server:
  port: 7073
cloud:
  aws:
    credentials:
      access-key: AKIAUDUM6GSLAFHR2RFS
      secret-key: 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
    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: springboot3hrmanagement
spring:
  rabbitmq:
    host: 10.112.6.155
    port: 5672
    username: user
    password: user
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${POSTGREPW}
    url: jdbc:postgresql://34.41.238.196:6060/CompanyServiceDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rabbitmq:
  auth-exchange: auth-exchange
  register-binding-key: register-key
  register-queue: register-queue
  activation-binding-key: activation-key
  activation-queue: queue-activation
  mail-queue: mail-queue
  mail-binding-key: mail-binding-key
  company-queue: company-queue
  company-binding-key: company-binding-key
  company-queue2: company-queue2
  company-binding-key2: company-binding-key2
  company-queue3: company-queue2
  company-binding-key3: company-binding-key2
  expense-queue: expense-queue
  expense-binding-key: expense-binding-key
